specificationVersion: environment-2023-09
parameterDefinitions:
- name: Value
  type: INT
  allowedValues:
  - 10
  - 20
  default: 0
environment:
  name: TestEnv
  variables:
    VAL: '{{Param.Value}}'
