template:
  specificationVersion: jobtemplate-2023-09
  name: TestJob
  steps:
  - name: Step1
    parameterSpace:
      taskParameterDefinitions:
      - name: Val
        type: INT
        range: 1,3,5,7
    script:
      actions:
        onRun:
          command: python
          args:
          - -c
          - print(r'VAL:{{Task.Param.Val}}')
expected:
  output:
  - VAL:1
  - VAL:3
  - VAL:5
  - VAL:7
  forbidden:
  - VAL:0
  - VAL:8
