specificationVersion: jobtemplate-2023-09
name: TestJob
parameterDefinitions:
- name: MyParam
  type: STRING
  allowedValues:
  - option1
  - option2
  userInterface:
    control: HIDDEN
steps:
- name: Step1
  script:
    actions:
      onRun:
        command: echo
        args:
        - "{{Param.MyParam}}"
