specificationVersion: jobtemplate-2023-09
name: TestJob
parameterDefinitions:
- name: MyParam
  type: INT
  allowedValues:
  - "1"
  - "2"
  - "4"
steps:
- name: Step1
  script:
    actions:
      onRun:
        command: echo
        args:
        - "{{Param.MyParam}}"
