specificationVersion: environment-2023-09
environment:
  name: TestEnv
  script:
    actions:
      onEnter:
        command: python
        args:
        - "-c"
        - "print(r'entering')"
      onExit:
        command: python
        args:
        - "-c"
        - "print(r'exiting')"
