specificationVersion: environment-2023-09
parameterDefinitions:
- name: Foo
  type: INT
  allowedValues:
  - 10
  - 20
  - 30
  minValue: 0
  maxValue: 40
  default: 20
environment:
  name: TestEnv
  variables:
    FOO: '{{Param.Foo}}'
