specificationVersion: environment-2023-09
parameterDefinitions:
- name: Value
  type: STRING
  allowedValues:
  - aaa
  - bbbbb
  - cccccc
  minLength: 1
  maxLength: 9
  default: aaa
environment:
  name: TestEnv
  variables:
    VAL: '{{Param.Value}}'
