template:
  specificationVersion: jobtemplate-2023-09
  name: TestJob
  parameterDefinitions:
  - name: Value
    type: STRING
    allowedValues:
    - bbbbb
    - cccccc
    minLength: 2
    maxLength: 10
    default: bbbbb
  steps:
  - name: Step1
    script:
      actions:
        onRun:
          command: python
          args:
          - -c
          - print(r'Value={{Param.Value}}')
environments:
- specificationVersion: environment-2023-09
  parameterDefinitions:
  - name: Value
    type: STRING
    allowedValues:
    - aaa
    - bbbbb
    - cccccc
    minLength: 1
    maxLength: 9
    default: aaa
  environment:
    name: TestEnv
    variables:
      VAL: '{{Param.Value}}'
expected:
  output:
  - Value=bbbbb
  forbidden:
  - Value=aaa
