name: 'Check stale issues/PRs.'
on: 
  schedule:
    # Run every hour on the hour
    - cron: '0 * * * *'

jobs:
  check-for-stales:
    uses: OpenJobDescription/.github/.github/workflows/reusable_stale_prs_and_issues.yml@mainline
    permissions:
      contents: read
      issues: write
      pull-requests: write
